name: Test OpenBSD Port

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-openbsd-port:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start OpenBSD VM
        id: vm
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.6"
          sync: nfs
          prepare: |
            pkg_add -u
            pkg_add autoconf automake libtool gmake git libev mbedtls pcre libsodium libcares  

      - name: Install ports tree
        shell: openbsd {0}
        run: |
          echo "Verifying execution inside OpenBSD VM"
          uname -a
          whoami
          echo "Starting ports tree installation"
          ping -c 4 cdn.openbsd.org || (echo "Network unreachable" && exit 1)
          curl -L -o /tmp/ports.tar.gz https://cdn.openbsd.org/pub/OpenBSD/7.6/ports.tar.gz || (echo "Failed to download ports.tar.gz" && exit 1)
          ls -lh /tmp/ports.tar.gz
          tar -tzf /tmp/ports.tar.gz | grep infrastructure/mk/bsd.port.mk || (echo "bsd.port.mk not in tarball" && exit 1)
          tar -xzvf /tmp/ports.tar.gz -C /usr/ || (echo "Failed to extract ports.tar.gz" && exit 1)
          rm /tmp/ports.tar.gz
          ls -l /usr/ports/infrastructure/mk/bsd.port.mk || (echo "bsd.port.mk not found" && exit 1)
          echo "Ports tree installed successfully"

      - name: Copy port files and generate distinfo
        shell: openbsd {0}
        run: |
          echo "Copying port files"
          ls -l $GITHUB_WORKSPACE/net/shadowsocks-libev/ || (echo "Source directory not found" && exit 1)
          mkdir -p /usr/ports/net/shadowsocks-libev/patches
          cp -r $GITHUB_WORKSPACE/net/shadowsocks-libev/* /usr/ports/net/shadowsocks-libev/ || (echo "Copy failed" && exit 1)
          cd /usr/ports/net/shadowsocks-libev
          ls -l .  # Verify directory contents
          ls -l patches/  # Verify patch file if exists
          cat -et Makefile
          cat Makefile > Makefile_debug.txt
          echo "Generating distinfo"
          make makesum || (echo "Failed to generate distinfo for tarball" && exit 1)
          if [ -f patches/patch-libcork_src_libcork_posix_env_c ]; then
            sha256 patches/patch-libcork_src_libcork_posix_env_c | awk '{print "SHA256 (" $4 ") = " $1}' >> distinfo
            wc -c patches/patch-libcork_src_libcork_posix_env_c | awk '{print "SIZE (" $2 ") = " $1}' >> distinfo
          fi
          cat distinfo  # Log distinfo contents
          echo "Port files copied and distinfo generated"

      - name: Build and package with debug output
        shell: openbsd {0}
        run: |
          echo "Starting build"
          cd /usr/ports/net/shadowsocks-libev
          ls -l /usr/ports/infrastructure/mk/bsd.port.mk || (echo "bsd.port.mk missing before make" && exit 1)
          ls -l distinfo || (echo "distinfo missing" && exit 1)
          make -d A NO_DEPENDS=1 fetch > fetch_debug.txt 2>&1 || (cat fetch_debug.txt && exit 1)
          make NO_DEPENDS=1 patch
          make NO_DEPENDS=1
          make NO_DEPENDS=1 install
          make NO_DEPENDS=1 package
          ls -lh /usr/ports/packages/$(uname -m)/all/
          echo "Copying artifacts to host workspace"
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp /usr/ports/net/shadowsocks-libev/fetch_debug.txt $GITHUB_WORKSPACE/artifacts/
          cp /usr/ports/net/shadowsocks-libev/Makefile_debug.txt $GITHUB_WORKSPACE/artifacts/
          cp /usr/ports/net/shadowsocks-libev/distinfo $GITHUB_WORKSPACE/artifacts/
          cp /usr/ports/packages/amd64/all/shadowsocks-libev-3.3.5p3.tgz $GITHUB_WORKSPACE/artifacts/
          echo "Build completed"

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            ${{ github.workspace }}/artifacts/fetch_debug.txt
            ${{ github.workspace }}/artifacts/Makefile_debug.txt
            ${{ github.workspace }}/artifacts/distinfo

      - name: Upload package artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: shadowsocks-libev-package
          path: ${{ github.workspace }}/artifacts/shadowsocks-libev-3.3.5p3.tgz
